/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-06-03 06:28:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import javax.naming.*;
import javax.sql.*;
import java.io.*;

public final class adminindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.naming");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>MRU SPORTS HUB ADMIN</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"images/png\" href=\"images/mru logo.png\"/>\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  </head>\r\n");
      out.write(" <body>\r\n");
      out.write("  <!--logo-->\r\n");
      out.write("  <section>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-body-tertiary\">\r\n");
      out.write("      <div class=\"rows\">\r\n");
      out.write("          <div class=\"logo\">\r\n");
      out.write("              <img src=\"images/mrulogo1.jpg\" alt=\"\">\r\n");
      out.write("              <p>MRU SPORTS HUB</p>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <br><br> \r\n");
      out.write("    <div>\r\n");
      out.write("    <marquee scrollamount=10><b class=\"admin\">Welcome Admin!!</b></marquee>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--banner--> \r\n");
      out.write("    <div id=\"carouselExampleCaptions\" class=\"carousel slide\">\r\n");
      out.write("        <div class=\"carousel-indicators\">\r\n");
      out.write("          <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("          <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("          <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("          <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"3\" aria-label=\"Slide 4\"></button>\r\n");
      out.write("          <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"4\" aria-label=\"Slide 5\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("          <div class=\"carousel-item active\">\r\n");
      out.write("            <img src=\"images/cricketbanner.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>CRICKET</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"images/hockeybanner.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>HOCKEY</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"images/kabaddibanner.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>KABADDI</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"images/Volleyball banner.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>VOLLEY BALL</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div><div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"images/footballbanner.jpg\" class=\"d-block w-100\" alt=\"...\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("              <h5>FOOT BALL</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("        </button>\r\n");
      out.write("      </div>\r\n");
      out.write("  </section>\r\n");
      out.write("   <h1>Live Matches</h1>\r\n");
      out.write("    <div class=\"liveedit\">\r\n");
      out.write("        <a href=\"Match-entry.jsp\" class=\"btn btn-primary\">New</a>\r\n");
      out.write("        <a href=\"remove-match.jsp\" class=\"btn btn-danger\">Remove</a>\r\n");
      out.write("        <a href=\"live-score.jsp\" class=\"btn btn-primary\">Live Score</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"live\">\r\n");
      out.write("        <div class=\"swipe-indicator left\">\r\n");
      out.write("            <i class=\"fas fa-chevron-left\"></i> Swipe\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"scroll-container\" id=\"scroll-container\">\r\n");
      out.write("            ");

                Connection conn = null;
                PreparedStatement ps = null;
                ResultSet rs = null;

                String url = "jdbc:mysql://localhost:3306/login";
                String username = "root";
                String password = "mysql";

                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    conn = DriverManager.getConnection(url, username, password);

                    String sql = "SELECT matchentry.match_id, matchentry.sportstype, matchentry.team1, matchentry.team1_logo, matchentry.team2, matchentry.team2_logo, " +
                                 "livescore.team1_score, livescore.team1_wickets, livescore.team1_overs, livescore.team2_score, livescore.team2_wickets, livescore.team2_overs, " +
                                 "other_sports_scores.team1_score AS other_team1_score, other_sports_scores.team2_score AS other_team2_score " +
                                 "FROM matchentry " +
                                 "LEFT JOIN livescore ON matchentry.match_id = livescore.match_id " +
                                 "LEFT JOIN other_sports_scores ON matchentry.match_id = other_sports_scores.match_id " +
                                 "ORDER BY matchentry.created_at DESC";
                    ps = conn.prepareStatement(sql);
                    rs = ps.executeQuery();

                    while (rs.next()) {
                        int match_id = rs.getInt("match_id");
                        String sportstype = rs.getString("sportstype");
                        String team1 = rs.getString("team1");
                        byte[] team1Logo = rs.getBytes("team1_logo");
                        String team2 = rs.getString("team2");
                        byte[] team2Logo = rs.getBytes("team2_logo");

                        int team1_score = rs.getInt("team1_score");
                        int team1_wickets = rs.getInt("team1_wickets");
                        String team1_overs = rs.getString("team1_overs");
                        int team2_score = rs.getInt("team2_score");
                        int team2_wickets = rs.getInt("team2_wickets");
                        String team2_overs = rs.getString("team2_overs");

                        int other_team1_score = rs.getInt("other_team1_score");
                        int other_team2_score = rs.getInt("other_team2_score");

                        String team1LogoBase64 = Base64.getEncoder().encodeToString(team1Logo);
                        String team2LogoBase64 = Base64.getEncoder().encodeToString(team2Logo);
                        
      out.write("\r\n");
      out.write("                        <div class=\"match-box\">\r\n");
      out.write("                            <h2>");
      out.print( sportstype );
      out.write("</h2>\r\n");
      out.write("                            <h2>Match ID: ");
      out.print( match_id );
      out.write("</h2>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                ");
      out.print( team1 );
      out.write(" \r\n");
      out.write("                                <img src=\"data:image/jpeg;base64,");
      out.print( team1LogoBase64 );
      out.write("\" alt=\"");
      out.print( team1 );
      out.write(" logo\">\r\n");
      out.write("                                ");
 if ("Cricket".equalsIgnoreCase(sportstype)) { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( team1_score );
      out.write('/');
      out.print( team1_wickets );
      out.write(' ');
      out.write('(');
      out.print( team1_overs );
      out.write(")\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( other_team1_score );
      out.write("\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <p>\r\n");
      out.write("                                ");
      out.print( team2 );
      out.write(" \r\n");
      out.write("                                <img src=\"data:image/jpeg;base64,");
      out.print( team2LogoBase64 );
      out.write("\" alt=\"");
      out.print( team2 );
      out.write(" logo\">\r\n");
      out.write("                                ");
 if ("Cricket".equalsIgnoreCase(sportstype)) { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( team2_score );
      out.write('/');
      out.print( team2_wickets );
      out.write(' ');
      out.write('(');
      out.print( team2_overs );
      out.write(")\r\n");
      out.write("                                ");
 } else { 
      out.write("\r\n");
      out.write("                                    - ");
      out.print( other_team2_score );
      out.write("\r\n");
      out.write("                                ");
 } 
      out.write("\r\n");
      out.write("                            </p>\r\n");
      out.write("                            ");
 if ("Cricket".equalsIgnoreCase(sportstype)) { 
      out.write("\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/CricketTeamServlet?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">Edit team</a>\r\n");
      out.write("                                <a href=\"selected-cricket-team.jsp?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">View team</a>\r\n");
      out.write("                            ");
 } else if ("Volleyball".equalsIgnoreCase(sportstype)) { 
      out.write("\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/VolleyballTeamServlet?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">Edit team</a>\r\n");
      out.write("                                <a href=\"Selected-volleyball-team.jsp?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">View team</a>\r\n");
      out.write("                            ");
 } else if ("Football".equalsIgnoreCase(sportstype)) { 
      out.write("\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/FootballTeamServlet?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">Edit team</a>\r\n");
      out.write("                                <a href=\"Selected-football-team.jsp?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">View team</a>\r\n");
      out.write("                            ");
 } else if ("Hockey".equalsIgnoreCase(sportstype)) { 
      out.write("\r\n");
      out.write("                                <a href=\"");
      out.print( request.getContextPath() );
      out.write("/HockeyTeamServlet?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">Edit team</a>\r\n");
      out.write("                                <a href=\"selected-hockey-team.jsp?match_id=");
      out.print( match_id );
      out.write("\" class=\"btn btn-primary\">View team</a>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");

                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    response.getWriter().println("Error: " + e.getMessage());
                } finally {
                    if (rs != null) try { rs.close(); } catch (SQLException e) { }
                    if (ps != null) try { ps.close(); } catch (SQLException e) { }
                    if (conn != null) try { conn.close(); } catch (SQLException e) { }
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"swipe-indicator right\">\r\n");
      out.write("            Swipe <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <section class=\"header\">\r\n");
      out.write("    <div class=\"containeer\">\r\n");
      out.write("        <div class=\"row padboth\">   \r\n");
      out.write("  			<h1>SPORTS TEAMS</h1>\r\n");
      out.write("            <div class=\"items\">\r\n");
      out.write("             <img src=\"images/cricket.jpg\" alt=\"\">\r\n");
      out.write("             <div class=\"inneritem\">\r\n");
      out.write("                <a href=\"cricket-team-admin1.jsp\"><h3>CRICKET</h3></a>\r\n");
      out.write("\r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"items\">\r\n");
      out.write("             <img src=\"images/vollyball.jpg\" alt=\"\">\r\n");
      out.write("             <div class=\"inneritem\">\r\n");
      out.write("                <a href=\"volleyball-team-admin1.jsp\"><h3>VOLLEY BALL</h3></a>\r\n");
      out.write("\r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"items\">\r\n");
      out.write("                <img src=\"images/football.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"inneritem\">\r\n");
      out.write("                    <a href=\"football-team-admin1.jsp\"><h3>FOOT BALL</h3></a>\r\n");
      out.write("      \r\n");
      out.write("                 </div>\r\n");
      out.write("                 \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"items\">\r\n");
      out.write("              <img src=\"images/hockey.jpg\" alt=\"\">\r\n");
      out.write("              <div class=\"inneritem\"><br>\r\n");
      out.write("                  <a href=\"hockey-team-admin1.jsp\"><h3>HOCKEY</h3></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("                  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!--footer -->\r\n");
      out.write("  <section>\r\n");
      out.write("    <footer>\r\n");
      out.write("      <div class=\"footer-top\">\r\n");
      out.write("          <div class=\"contaiiner\">\r\n");
      out.write("              <div class=\"footer-day-time\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                      <div class=\"col-lg-4\">\r\n");
      out.write("                        \r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"support\">\r\n");
      out.write("                      <h3><b>Support & Feedback</b></h3>\r\n");
      out.write("                       </div><br>\r\n");
      out.write("                  <div class=\"para\"> \r\n");
      out.write("                    \r\n");
      out.write("                      <p><b>You can send Feedback and get support via mail from the setting of out apps which provides us with detail about the version of the app you are running.</b></p>\r\n");
      out.write("                       <br><p><b> You can also get help on twitter via our app accounts.Follow them to get tips and updates</b>\r\n");
      out.write("                      </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"support\">\r\n");
      out.write("                      <h3><b>Email support</b></h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <br>\r\n");
      out.write("                      <ul class=\"address1\">\r\n");
      out.write("                          <li><i class='bx bx-envelope' ></i><a href=\"\":#> support@mrusportshub.com</a></li>\r\n");
      out.write("                          <li><i class='bx bx-envelope' ></i><a href=\"mailto:#\"> mrusportshub.com</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                      \r\n");
      out.write("                      \r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-4\">\r\n");
      out.write("                    <div class=\"support\">\r\n");
      out.write("                      <h3><b>Follow us </b></h3>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <br>\r\n");
      out.write("                  <ul>\r\n");
      out.write("                      <div class=\"addr1\">\r\n");
      out.write("                          <li><i class=\"fa fa-facebook\"></i><b>Facebook:</b> <a href=\"https://www.facebook.com/mrusportshub\">mrusportshub</a></li>\r\n");
      out.write("                          <li> <i class=\"fa fa-instagram\"></i> <b>Instagram:</b><a href=\"mailto:mrusportshub_123\"> mrusportshub_123</a></li>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                  \r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("  </section>\r\n");
      out.write("  <section>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <p>Copyright &copy2024; Designed by <span class=\"designer\">SPORTS TEAM</span></p>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/hammerjs@2.0.8/hammer.min.js\"></script>\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  	<script>\r\n");
      out.write("  	document.addEventListener(\"DOMContentLoaded\", () => {\r\n");
      out.write("        const container = document.getElementById('scroll-container');\r\n");
      out.write("        const hammer = new Hammer(container);\r\n");
      out.write("\r\n");
      out.write("        // Mouse drag scrolling\r\n");
      out.write("        let isDown = false;\r\n");
      out.write("        let startX;\r\n");
      out.write("        let scrollLeft;\r\n");
      out.write("\r\n");
      out.write("        container.addEventListener('mousedown', (e) => {\r\n");
      out.write("            isDown = true;\r\n");
      out.write("            startX = e.pageX - container.offsetLeft;\r\n");
      out.write("            scrollLeft = container.scrollLeft;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        container.addEventListener('mouseleave', () => {\r\n");
      out.write("            isDown = false;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        container.addEventListener('mouseup', () => {\r\n");
      out.write("            isDown = false;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        container.addEventListener('mousemove', (e) => {\r\n");
      out.write("            if (!isDown) return;\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const x = e.pageX - container.offsetLeft;\r\n");
      out.write("            const walk = (x - startX) * 3; //scroll-fast\r\n");
      out.write("            container.scrollLeft = scrollLeft - walk;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Touch swipe scrolling\r\n");
      out.write("        hammer.get('swipe').set({ direction: Hammer.DIRECTION_HORIZONTAL });\r\n");
      out.write("\r\n");
      out.write("        hammer.on('swipeleft', () => {\r\n");
      out.write("            container.scrollBy({ left: 300, behavior: 'smooth' });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        hammer.on('swiperight', () => {\r\n");
      out.write("            container.scrollBy({ left: -300, behavior: 'smooth' });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("  	\r\n");
      out.write("    function openMatchPage(sportstype, matchId) {\r\n");
      out.write("        console.log(\"Sport Type: \" + sportstype);\r\n");
      out.write("        console.log(\"Match ID: \" + matchId);\r\n");
      out.write("        var url;\r\n");
      out.write("        switch (sportstype) {\r\n");
      out.write("            case 'Cricket':\r\n");
      out.write("                url = 'selected-cricket-team.jsp#' + matchId;\r\n");
      out.write("                break;\r\n");
      out.write("            case 'Football':\r\n");
      out.write("                url = 'selected-football-team.jsp#' + matchId;\r\n");
      out.write("                break;\r\n");
      out.write("            case 'Hockey':\r\n");
      out.write("                url = 'selected-hockey-team.jsp#' + matchId;\r\n");
      out.write("                break;\r\n");
      out.write("            case 'Volleyball':\r\n");
      out.write("                url = 'selected-volleyball-team.jsp#' + matchId;\r\n");
      out.write("                break;\r\n");
      out.write("            default:\r\n");
      out.write("                alert('Unknown sport type!');\r\n");
      out.write("                return;\r\n");
      out.write("        }\r\n");
      out.write("        console.log(\"Redirecting to: \" + url);\r\n");
      out.write("        window.location.href = url;\r\n");
      out.write("    }\r\n");
      out.write("    // Function to refresh the page every 30 seconds\r\n");
      out.write("    setInterval(function() {\r\n");
      out.write("        location.reload();}, 60000); \r\n");
      out.write("</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
      out.write("<style>\r\n");
      out.write(" font-family: 'Lato', sans-serif;\r\n");
      out.write("font-family: 'Sevillana', cursive; \r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700&family=Sevillana&display=swap'); .\r\n");
      out.write("\r\n");
      out.write(".rows{\r\n");
      out.write("  background: #fff;\r\n");
      out.write("  height: 240;\r\n");
      out.write("  width:100%;\r\n");
      out.write("  background-color:white;\r\n");
      out.write("}\r\n");
      out.write(".logo {\r\n");
      out.write("    display: flex; /* Use flexbox for the logo container */\r\n");
      out.write("    align-items: center; /* Center items vertically */\r\n");
      out.write("    width: 1400px;\r\n");
      out.write("    height: 200px;\r\n");
      out.write("  background-color:white;\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    .logo p{\r\n");
      out.write("  font-family: \"Playfair Display\", serif;\r\n");
      out.write("  font-optical-sizing: auto;\r\n");
      out.write("  font-weight: 400;\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("  color: #555;\r\n");
      out.write("  font-size: 110px;\r\n");
      out.write("  padding-left: 100px;\r\n");
      out.write("  padding:100px;\r\n");
      out.write("  background-color:white;\r\n");
      out.write("}\r\n");
      out.write(".logo img {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("}\r\n");
      out.write("/*footer*/\r\n");
      out.write(".fa {\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  width: 30px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  margin: 5px 2px;\r\n");
      out.write("}\r\n");
      out.write(".fa:hover {\r\n");
      out.write("    opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa-facebook {\r\n");
      out.write("  \r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".bx-envelope{\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".fa-instagram {\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write(".para{\r\n");
      out.write("  color: #fae9e9e3;\r\n");
      out.write("}\r\n");
      out.write(".addr1{\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".addr1 li{\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write(".addr1 li a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  transition: transform 0.5s;\r\n");
      out.write("}\r\n");
      out.write(".address1 li{\r\n");
      out.write("  display: block;\r\n");
      out.write("}\r\n");
      out.write(".address1 li a{\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  transition: transform 0.5s;\r\n");
      out.write("}\r\n");
      out.write(".addr1 li a:hover{\r\n");
      out.write("  color: #8ea22b;\r\n");
      out.write("    transform: translateY(-5px);\r\n");
      out.write("}\r\n");
      out.write(".address1 li a:hover{\r\n");
      out.write("  color: #8ea22b;\r\n");
      out.write("    transform: translateY(-5px);\r\n");
      out.write("}\r\n");
      out.write(".support{\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: #fffdfd;\r\n");
      out.write("}\r\n");
      out.write(".footer-top{\r\n");
      out.write("  background-color: #3f3c3c;\r\n");
      out.write("    height: 250px;\r\n");
      out.write("}\r\n");
      out.write("/*banner down*/\r\n");
      out.write("\r\n");
      out.write(".header{\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".containeer{\r\n");
      out.write("  max-width: 1200px; \r\n");
      out.write("    margin: 0 auto; \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".pading50{\r\n");
      out.write("    padding-top:50px;\r\n");
      out.write("}\r\n");
      out.write(".padboth{\r\n");
      out.write("    padding:10px 10px;\r\n");
      out.write("}\r\n");
      out.write(".items{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:auto;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin:15px;\r\n");
      out.write("    border:1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write(".items img{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    height:auto;\r\n");
      out.write("}\r\n");
      out.write(".inneritem{\r\n");
      out.write("padding:15px;\r\n");
      out.write("}\r\n");
      out.write(".inneritem h3{\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color:#481fa6;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 10px 0px;\r\n");
      out.write("}\r\n");
      out.write(".inneritem h3:hover{\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write(".items:hover{\r\n");
      out.write("    box-shadow: 0px 0px 10px #ddd;\r\n");
      out.write("    background-color:black;\r\n");
      out.write("}\r\n");
      out.write(".inneritem a{\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(".items{\r\n");
      out.write("    width:268px;\r\n");
      out.write("    height:auto;\r\n");
      out.write("    float: left;\r\n");
      out.write("    margin:15px;\r\n");
      out.write("    border:1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("  #navlist {\r\n");
      out.write("			width: 100%;\r\n");
      out.write("		}\r\n");
      out.write("    #navlist a {\r\n");
      out.write("			float:right;\r\n");
      out.write("			display: block;\r\n");
      out.write("			color: #0d0d0d;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			padding: 12px;\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		.navlist-right{\r\n");
      out.write("			float:right;\r\n");
      out.write("		}\r\n");
      out.write("		#navlist a:hover {\r\n");
      out.write("			background-color: #d8d5d5;\r\n");
      out.write("			color: black;\r\n");
      out.write("		}\r\n");
      out.write("    .login{\r\n");
      out.write("      background-color: rgb(234, 156, 55);\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("  .login h5{\r\n");
      out.write("    color: white;\r\n");
      out.write("    transition: ease-in .3s;\r\n");
      out.write("  }\r\n");
      out.write("  .login h5:hover{\r\n");
      out.write("    color: black;\r\n");
      out.write("    }\r\n");
      out.write("    /* footer */\r\n");
      out.write(".footer{\r\n");
      out.write("    background-color: #1f1a1c;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("     width:1500px;\r\n");
      out.write("}\r\n");
      out.write(".footer p{\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write(".designer{\r\n");
      out.write("    opacity: 0.7;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    margin: 0px 5px;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".admin{\r\n");
      out.write("	font-size:50px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("       body{ font-family: 'Lato', sans-serif;\r\n");
      out.write("            background: linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .live {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .scroll-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            transition: transform 0.3s ease-in-out;\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("            scroll-behavior: smooth;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .scroll-container::-webkit-scrollbar {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .scroll-container {\r\n");
      out.write("            -ms-overflow-style: none;\r\n");
      out.write("            scrollbar-width: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .match-box {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            flex: 0 0 auto;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("            transition: transform 0.3s, box-shadow 0.3s;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .match-box:hover {\r\n");
      out.write("            transform: translateY(-10px);\r\n");
      out.write("            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .match-box img {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-left: auto;\r\n");
      out.write("            margin-right: auto;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .match-box h2 {\r\n");
      out.write("            font-family: 'Lato', sans-serif;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            color: #ff4081;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .match-box p {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            color: #555;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .match-box p img {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-family: 'Lato', sans-serif;\r\n");
      out.write("            font-size: 36px;\r\n");
      out.write("            color: #ff4081;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .swipe-indicator {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translateY(-50%);\r\n");
      out.write("            color: #ff4081;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .swipe-indicator.left {\r\n");
      out.write("            left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .swipe-indicator.right {\r\n");
      out.write("            right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .swipe-indicator i {\r\n");
      out.write("            margin: 0 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .liveedit {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: flex-end; \r\n");
      out.write("    gap: 10px;\r\n");
      out.write("    padding-bottom:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".liveedit a {\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    background-color: rgb(234, 156, 55);\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
