/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-06-02 06:00:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cricketteam_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Enter Cricket Player Details</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"images/png\" href=\"images/mru logo.png\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <h1>Enter Cricket Player Details</h1>\r\n");
      out.write("    <form action=\"cricketPlayerDetails\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        <label for=\"playerName\">Player Name:</label>\r\n");
      out.write("        <input type=\"text\" id=\"playerName\" name=\"playerName\" required><br>\r\n");
      out.write("        <label for=\"playerType\">Player Type:</label>\r\n");
      out.write("        <select id=\"playerType\" name=\"playerType\" required>\r\n");
      out.write("            <option value=\"\">Select Type</option>\r\n");
      out.write("            <option value=\"Batsman\">Batsman</option>\r\n");
      out.write("            <option value=\"Bowler\">Bowler</option>\r\n");
      out.write("            <option value=\"Wicket Keeper\">Wicket Keeper</option>\r\n");
      out.write("            <option value=\"All Rounder\">All Rounder</option>\r\n");
      out.write("        </select><br>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"totalRuns\">Total Runs:</label>\r\n");
      out.write("        <input type=\"number\" id=\"totalRuns\" name=\"totalRuns\" required><br>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"bowlingDetails\" style=\"display:none;\">\r\n");
      out.write("		    <label for=\"bowlingType\">Bowling Type:</label>\r\n");
      out.write("		    <select id=\"bowlingType\" name=\"bowlingType\" >\r\n");
      out.write("		    <option value=\"\">Select Type</option>\r\n");
      out.write("		        <option value=\"Fast\">Fast</option>\r\n");
      out.write("		        <option value=\"Spin\">Spin</option>\r\n");
      out.write("		        <option value=\"Medium\">Medium</option>\r\n");
      out.write("		    </select><br>  \r\n");
      out.write("		 </div>\r\n");
      out.write("		 <div id=\"bowlerDetails\" style=\"display:none;\">          \r\n");
      out.write("		    <label for=\"wickets\">Wickets:</label>\r\n");
      out.write("		    <input type=\"number\" id=\"bowlerWickets\" name=\"bowlerWickets\" ><br>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"wicketKeeperDetails\" style=\"display:none;\">\r\n");
      out.write("		    <label for=\"stumpings\">Stumpings:</label>\r\n");
      out.write("		    <input type=\"number\" id=\"stumpings\" name=\"stumpings\" ><br>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"allRounderDetails\" style=\"display:none;\">\r\n");
      out.write("		    <label for=\"wickets\">Wickets:</label>\r\n");
      out.write("		    <input type=\"number\" id=\"allRounderWickets\" name=\"allrounderWickets\" ><br>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <label for=\"catches\">Catches:</label>\r\n");
      out.write("        <input type=\"number\" id=\"catches\" name=\"catches\" required><br>\r\n");
      out.write("        \r\n");
      out.write("        <label for=\"useDefaultImage\">Use Default Image:</label>\r\n");
      out.write("		<input type=\"checkbox\" id=\"useDefaultImage\" name=\"useDefaultImage\">\r\n");
      out.write("        \r\n");
      out.write("         <input type=\"file\" id=\"playerPhoto\" name=\"playerPhoto\" accept=\"image/*\" ><br>\r\n");
      out.write("        <input type=\"submit\" value=\"Submit\">\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        document.getElementById('playerType').addEventListener('change', function(event) {\r\n");
      out.write("            var value = event.target.value;\r\n");
      out.write("            document.getElementById(\"bowlingDetails\").style.display = (value === \"Bowler\" || value === \"All Rounder\") ? \"block\" : \"none\";\r\n");
      out.write("            document.getElementById(\"bowlerDetails\").style.display = value === \"Bowler\" ? \"block\" : \"none\";\r\n");
      out.write("            document.getElementById(\"wicketKeeperDetails\").style.display = value === \"Wicket Keeper\" ? \"block\" : \"none\";\r\n");
      out.write("            document.getElementById(\"allRounderDetails\").style.display = value === \"All Rounder\" ? \"block\" : \"none\";\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('useDefaultImage').addEventListener('change', function(event) {\r\n");
      out.write("            var playerPhotoInput = document.getElementById('playerPhoto');\r\n");
      out.write("            playerPhotoInput.disabled = event.target.checked;\r\n");
      out.write("            playerPhotoInput.value = ''; // Clear any selected file\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  font-family: 'Lato', sans-serif;\r\n");
      out.write("font-family: 'Sevillana', cursive; \r\n");
      out.write("\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Lato:wght@100;300;400;700&family=Sevillana&display=swap'); \r\n");
      out.write("\r\n");
      out.write("*{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: \"poppins\",sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("body {\r\n");
      out.write("    background: url('images/cricketbg.jpg');\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    background-position: center; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	padding-top:90px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("	padding-top:10px;\r\n");
      out.write("    max-width: 400px;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.5); /* Transparent white background */\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("    color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"],\r\n");
      out.write("input[type=\"number\"],\r\n");
      out.write("select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("    appearance: none;\r\n");
      out.write("    -webkit-appearance: none;\r\n");
      out.write("    -moz-appearance: none;\r\n");
      out.write("    background-image: url('data:image/svg+xml;utf8,<svg fill=\"black\" height=\"24\" viewBox=\"0 0 24 24\" width=\"24\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M7 10l5 5 5-5z\"/><path d=\"M0 0h24v24H0z\" fill=\"none\"/></svg>');\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-position-x: calc(100% - 10px);\r\n");
      out.write("    background-position-y: center;\r\n");
      out.write("    padding-right: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"] {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 4px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"submit\"]:hover {\r\n");
      out.write("    background-color: #45a049;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#error-message {\r\n");
      out.write("    color: red;\r\n");
      out.write("    margin-top: 5px;\r\n");
      out.write("}\r\n");
      out.write("#bowlerDetails,\r\n");
      out.write("#wicketKeeperDetails,\r\n");
      out.write("#allRounderDetails {\r\n");
      out.write("    display: none;\r\n");
      out.write("}\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
