/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-06-03 06:45:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>MRU SportsHUB-Login</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"images/png\" href=\"images/mru logo.png\"/>\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form method=\"post\" action=\"login\" onsubmit=\"return validateLoginForm()\">\r\n");
      out.write("        <div class=\"container\"> \r\n");
      out.write("            <h1>Login</h1>\r\n");
      out.write("            <div class=\"input-box\"> \r\n");
      out.write("                <input type=\"text\" placeholder=\"Enter username or email\" id=\"username_or_email\" name=\"username_or_email\" required>\r\n");
      out.write("                <i class='bx bxs-user'></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"input-box\">  \r\n");
      out.write("            <input type=\"password\" placeholder=\"Enter password\" id=\"password\" name=\"password\" required>\r\n");
      out.write("            <i class='bx bxs-lock-alt'></i>\r\n");
      out.write("            ");
 String errorMessage = (String) request.getAttribute("errorMessage"); 
      out.write("\r\n");
      out.write("        ");
 if (errorMessage != null) { 
      out.write("\r\n");
      out.write("            <div id=\"error-message\" style=\"color: red;\">");
      out.print( errorMessage );
      out.write("</div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("                        <input type=\"submit\" class=\"btn\" value=\"Login\">\r\n");
      out.write("            <div class=\"register-link\">\r\n");
      out.write("                <p>Don't have an account?<a href=\"registration.jsp\">register</a></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div> \r\n");
      out.write("    </form>   \r\n");
      out.write("</body>    \r\n");
      out.write("<script>\r\n");
      out.write("    function hideErrorMessage() {\r\n");
      out.write("        setTimeout(function() {\r\n");
      out.write("            var errorMessage = document.getElementById(\"error-message\");\r\n");
      out.write("            if (errorMessage) {\r\n");
      out.write("                errorMessage.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }, 5000);\r\n");
      out.write("    }\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("        hideErrorMessage();\r\n");
      out.write("    };\r\n");
      out.write("    function showErrorMessage() {\r\n");
      out.write("        var errorMessage = document.getElementById(\"error-message\");\r\n");
      out.write("        if (errorMessage) {\r\n");
      out.write("            errorMessage.style.display = \"block\";\r\n");
      out.write("            hideErrorMessage();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("<style>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    *{\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        font-family: \"poppins\",sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    Body {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        background: url('images/login.jpg');\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        background-position: center; \r\n");
      out.write("    }\r\n");
      out.write("    .container{\r\n");
      out.write("        width: 420px;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        color: #f30909;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        padding: 30px 40px;\r\n");
      out.write("    }\r\n");
      out.write("    .container  h1{\r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .container .input-box{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        margin: 36px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .input-box input{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        border: none;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border: 2px solid red;\r\n");
      out.write("        border-radius: 40px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        color: #ea1919;\r\n");
      out.write("        padding: 20px 45px 20px 20px;\r\n");
      out.write("    }\r\n");
      out.write("    .input-box input::placeholder{\r\n");
      out.write("        color: #f30909;\r\n");
      out.write("    }\r\n");
      out.write("    .input-box i{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: 20px;\r\n");
      out.write("        top: 25px;\r\n");
      out.write("        transform: translateY(-50%);\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("    \r\n");
      out.write("        }\r\n");
      out.write("       \r\n");
      out.write("        .container .btn {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 45px;\r\n");
      out.write("            background: #775c9c;\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-radius: 40px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0,0,0,.1);\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .container .register-link{\r\n");
      out.write("        font-size: 14.4px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 20px ;\r\n");
      out.write("        }\r\n");
      out.write("        .register-link p a {\r\n");
      out.write("        color: #f30909;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("        .register-link p a:hover{\r\n");
      out.write("        text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("        .a{\r\n");
      out.write("            text-decoration: none ;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
